olark.configure('locale.welcome_title', "Chat with us!");
olark.configure('locale.chatting_title', "Now Chatting");
olark.configure('locale.unavailable_title', "Send us a message!");
olark.configure('locale.busy_title', "Currently busy");
olark.configure('locale.away_message', "We're not around, but you can use the form below to send us an email!");
olark.configure('locale.loading_title', "Loading Chat...");
olark.configure('locale.welcome_message', "Questions? We'd love to chat!");
olark.configure('locale.busy_message', "All of our employees are with other customers at this time. We will be with you shortly.");
olark.configure('locale.chat_input_text', "Type here and hit <enter> to chat");
olark.configure('locale.offline_note_message', "Your message");
olark.configure('locale.offline_note_thankyou_text', "Thanks for your message! We'll get back to you shortly.");
olark.configure('locale.offline_note_error_text', "You must complete all fields and specify a valid email address.");
olark.configure('locale.offline_note_sending_text', "Sending...");
olark.configure('locale.operator_is_typing_text', "is typing...");
olark.configure('locale.operator_has_stopped_typing_text', "has stopped typing");
olark.configure('locale.introduction_error_text', "Please leave a name and an email address so we can contact you in case we get disconnected.");
olark.configure('locale.introduction_messages', "Hi! Just fill out some brief information and click 'Start chat' to talk to us.");
olark.configure('locale.introduction_submit_button_text', "Start chat");
olark.configure('locale.disabled_input_text_when_convo_has_ended', "chat ended, refresh for new chat.");
olark.configure('locale.disabled_panel_text_when_convo_has_ended', "This conversation has ended, but all you need to do is refresh the page to start a new one!");
olark.configure('locale.name_input_text', "Your Name");
olark.configure('locale.phone_input_text', "Your phone number");
olark.configure('locale.email_input_text', "Your email");
olark.configure('locale.send_button_text', "Send");