olark.configure('locale.welcome_title', "Clavardez avec nous!");
olark.configure('locale.chatting_title', "Clavardage en cours");
olark.configure('locale.unavailable_title', "Envoyez-nous un message!");
olark.configure('locale.busy_title', "Occupé");
olark.configure('locale.away_message', "Nous ne sommes pas présent, mais vous pouvez utiliser le formulaire ci-dessous pour nous envoyer un courriel!");
olark.configure('locale.loading_title', "Chargement...");
olark.configure('locale.welcome_message', "Vous avez des questions? Nous serions ravis de discuter avec vous!");
olark.configure('locale.busy_message', "Tous nos employés sont occupés en ce moment. Nous serons avec vous sous peu!");
olark.configure('locale.chat_input_text', "Tapez ici et appuyez sur <entrer>");
olark.configure('locale.offline_note_message', "Votre message");
olark.configure('locale.offline_note_thankyou_text', "Merci de votre message! Nous prendrons contact avec vous sous peu.");
olark.configure('locale.offline_note_error_text', "Vous devez remplir tous les champs et spécifier une adresse courriel valide.");
olark.configure('locale.offline_note_sending_text', "Transmission...");
olark.configure('locale.operator_is_typing_text', "écrit...");
olark.configure('locale.operator_has_stopped_typing_text', "a cessé d'écrire");
olark.configure('locale.introduction_error_text', "SVP, laissez votre nom et courriel afin que nous puissions vous contacter au cas où nous serions déconnectés.");
olark.configure('locale.introduction_messages', "Salut! Il suffit de remplir quelques informations et cliquez sur «Clavarder» pour nous parler.");
olark.configure('locale.introduction_submit_button_text', "Clavarder");
olark.configure('locale.disabled_input_text_when_convo_has_ended', "discussion terminée, rafraîchir pour une nouvelle discussion.");
olark.configure('locale.disabled_panel_text_when_convo_has_ended', "discussion terminée, rafraîchir pour démarrer une nouvelle discussion.");
olark.configure('locale.name_input_text', "Votre nom");
olark.configure('locale.phone_input_text', "Votre numéro de téléphone");
olark.configure('locale.email_input_text', "Votre courriel");
olark.configure('locale.send_button_text', "Envoyer");