olark.configure('locale.welcome_title', "Beginne einen Live Chat");
olark.configure('locale.chatting_title', "Jetzt im Gespräch");
olark.configure('locale.unavailable_title', "Schick uns eine Nachricht!");
olark.configure('locale.busy_title', "Im Moment nicht verfügbar.");
olark.configure('locale.away_message', "Wir sind im Moment nicht da, mit dem Formular kannst du uns aber eine E-Mail schicken.");
olark.configure('locale.loading_title', "Chat wird geladen...");
olark.configure('locale.welcome_message', "Fragen? Wir würden gerne mit dir reden!");
olark.configure('locale.busy_message', "Alle unsere Mitarbeiter sind im Moment mit Kunden beschäftigt. Wir sind gleich bei Dir.");
olark.configure('locale.chat_input_text', "Schreib hier und drück Enter");
olark.configure('locale.offline_note_message', "Deine Nachricht");
olark.configure('locale.offline_note_thankyou_text', "Danke für Deine Nachricht. Wir melden uns in kürze bei Dir.");
olark.configure('locale.offline_note_error_text', "Du musst alle Felder ausfüllen und eine gültige Email Adresse angeben");
olark.configure('locale.offline_note_sending_text', "Wird gesendet...");
olark.configure('locale.operator_is_typing_text', "schreibt gerade...");
olark.configure('locale.operator_has_stopped_typing_text', "hat aufgehört zu schreiben");
olark.configure('locale.introduction_error_text', "Bitte hinterlass uns Deinen Namen und Email Adresse und wir nehmen mit Dir Kontakt auf sollte die Verbindung getrennt werden.");
olark.configure('locale.introduction_messages', "Hi! Bitte füll das Formular aus und klick auf 'Chat anfangen' um mit uns zu reden.");
olark.configure('locale.introduction_submit_button_text', "Chat anfangen");
olark.configure('locale.disabled_input_text_when_convo_has_ended', "Chat beendet, neu laden für neuen chat.");
olark.configure('locale.disabled_panel_text_when_convo_has_ended', "Dieses Gespräch wurde beendet. Du brauchst nur die Seite neu zuladen um ein neues Gespräch anzufangen.");
olark.configure('locale.name_input_text', "Dein Name");
olark.configure('locale.phone_input_text', "Deine Telefonnummer");
olark.configure('locale.email_input_text', "Deine Email");
olark.configure('locale.send_button_text', "Abschicken");